site_name: OpenCollector
site_url: http://localhost

theme:
  name: material
  features:
    - content.code.copy

plugins:
    - search
    - include-markdown

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: index.md
  - User Guide:
    - Usage: user-guide/usage.md
    - Setup: user-guide/setup.md
    - Collector:
      - PCB and Case: user-guide/collector/pcb.md
      - Config: user-guide/collector/config.md
      - Sensors: user-guide/collector/sensors.md
    - Storage:
      - Config: user-guide/storage/config.md
  - Developer Guide:
    - Overview: developer-guide/overview.md
    - Collector:
      - Sensors: developer-guide/collector/sensors.md
  - About: about.md
  - GitHub: https://github.com/compsust/openCollector
