def generate_unique_id(micropython: bool) -> str:
    """
    Generates a unique string ID.

    Args:
        micropython (bool): If true, the environment is micropython.
            For micropython, the string is generated by getting
            the unique ID of the device and appending a random string.
            Otherwise, the ID is generated with the UUID module.

    Returns:
        str: A unique ID.
    """
    if micropython:
        from machine import unique_id
        from urandom import choice

        chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        random_length = 8

        return str(unique_id().hex()) + "".join(
            choice(chars) for _ in range(random_length)
        )

    else:
        from uuid import uuid4

        return str(uuid4())
