[project]
name = "storage"
version = "0.1.0"
description = "The component of openCollector which interfaces with the database and provides data access."
dependencies = [
    "common",
    "litestar[standard]>=2.13.0",
    "asyncpg",
    "python-decouple",
    "bokeh>=3.7.2",
]
requires-python = ">= 3.12"

[tool.uv]
dev-dependencies = ["questdb", "typed-argument-parser"]

[tool.uv.sources]
common = { path = "../common" }
