[project]
name = "common"
version = "0.1.7"
description = "Python definitions common to both collector and storage nodes."
license = "MPL-2.0"
dependencies = []
requires-python = ">= 3.12"

[dependency-groups]
dev = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/common"]
