[project]
name = "common"
version = "0.1.3"
description = "Python definitions common to both collector and storage nodes."
dependencies = []
requires-python = ">= 3.12"

[tool.uv]
dev-dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/common"]